version: "3.8"
services:
  app:
    image: ghcr.io/lo-bzwu/portal
    volumes:
      - ./pb_data:/pb/pb_data

  # Reverse Proxy setup:
  # command: ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
  # ports:
  #   - "8080:8080"
      
  # Direct Production setup:
    command: ["/pb/pocketbase", "serve", ${TLS_DOMAIN}]
    ports:
      - "443:443"
      - "80:80"
  
    depends_on:
      - davinci-cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  davinci-cache:
    image: ghcr.io/lo-bzwu/davinci-cache
    environment:
      - DAVINCI_URL=${DAVINCI_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api-update --label-enable
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"


