version: "3.8"
services:
  app:
    image: ghcr.io/lo-bzwu/portal
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - "8080:8080"
    depends_on:
      - davinci-cache

  davinci-cache:
    image: ghcr.io/lo-bzwu/davinci-cache
    environment:
      - DAVINCI_URL=http://stundenplan.cl02.ch/daVinciIS.dll?content=json

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update --label-enable
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"


